### ISSUE TITLE
Ender IO Slice'N'Splice recipes not in JEI

### ISSUE THREAD

**Issue by wolpoff** [TheBritishBrotherhood/ArdentCraft-The-Beginning#74] opened 2017-01-16 21:10 UTC
Version 2.7.01

Ender IO recipes for use in the Slice'N'Splice aren't searchable.  They do build.  Z-logic Controller for instance shows no recipe, but it can be built in the Slice'N'Splice.  Just had to look it up on a wiki.

**Comment by vincentmet** [comment] 2017-01-16 22:35
Duplicate of #17

**Closed as completed by vincentmet** 2017-01-16 22:35 UTC
