### ISSUE TITLE
Quest Problems

### ISSUE THREAD

**Issue by ghost** [TheBritishBrotherhood/ArdentCraft-The-Beginning#61] opened 2016-12-31 16:30 UTC
I've found a few problems with quests, being that some things are impossible. The IC2 treetap is uncraftable, and the very first IC2 quest requires crafting 5 of them. The TechReborn treetap does not work for this quest, I did try. Also, pulsating iron is uncraftable as well. This is required for many things in Ender IO. That is all I know of for now, perhaps I am just making some mistake. Currently playing on 2.7.00. Thanks!

        ~CarlWheeser

**Comment by ghost** [comment] 2016-12-31 16:30
Looking back, I suppose this is more crafting issues than quest issues. It just makes some quests impossible.

**Comment by ghost** [comment] 2016-12-31 16:31
I now see I can still craft the treetap, JEI just didn't show it. Sorry! Probably the same with pulsating iron...

**Comment by vincentmet** [comment] 2016-12-31 17:18
Yeah, before posting an impossible-quest-issue, please check on the wiki/scripts if there is a recipe for it... Because this is an duplicate of #17

**Closed as completed by vincentmet** 2016-12-31 17:18 UTC
